[package]
name = "ws2812-esp32-rmt-driver"
version = "0.1.0"
license = "MIT"
authors = ["@cat_in_136"]
categories = ["embedded"]
description = "WS2812 driver using ESP32 RMT"
homepage = "https://github.com/cat-in-136/ws2812-esp32-rmt-smart-leds"
readme = "README.md"
repository = "https://github.com/cat-in-136/ws2812-esp32-rmt-smart-leds"
edition = "2018"
resolver = "2"

[features]
default = ["smart-leds-trait", "embedded-graphics-core"]
unstable = []

[dependencies]
smart-leds-trait = { version = "0.2", optional = true }
embedded-graphics-core = { version = "0.3", optional = true }
once_cell = "1"
thiserror = "1"

[target.'cfg(target_vendor = "espressif")'.dependencies]
esp-idf-sys = { version = "0.30", features = ["binstart"] }

[dev-dependencies]
smart-leds = "0.3"
embedded-graphics = "0.7"

[build-dependencies]
embuild = "0.28"
anyhow = "1"